### PR TITLE
[WIP] listed bundles removed and added in release notes -missing logic

### PR DESCRIPTION
**Pull request by mmartinm**
to filter-

### CODE REVIEW

**Comment by gtkramer** [comment]
Normally we run release notes at the start of a build.  I'm not sure we want to tie this to MCA execution which happens more toward the end of the build?  I'm open to being convinced otherwise :)

**Comment by mmartinm** [comment]
> Normally we run release notes at the start of a build. I'm not sure we want to tie this to MCA execution which happens more toward the end of the build? I'm open to being convinced otherwise :)

After the mixer finished it creates the MCA report for the new build and after that the release notes are created. So My assumption was why we cannot collect the bundle changes info from there.
probably we can discuss this reviewing the log

**Comment by gtkramer** [comment]
Ah, that's right.  I assume this is by intention in clr-distro-factory to have release notes generated at the end when things are successful.  I'm not sure if we want to depend on MCA in this case since in the pipelines we have on clr-distro-factory today in this repo, MCA is not called...

As things are right now, release notes are self-contained not needing MCA. I'm somewhat inclined to keep them this way given MCA is not in this pipeline?

**Comment by gtkramer** [comment]
Please also rebase your branch from master, squash your commits, and take a look at the Travis CI results listed below.

**Comment by mmartinm** [comment]
> Please also rebase your branch from master, squash your commits, and take a look at the Travis CI results listed below.

Ok, let's change the way comparing the bundles without dependecy of MCA and rebase the branch 
thanks

**Comment by mbelluzzo** [comment]
> Normally we run release notes at the start of a build. I'm not sure we want to tie this to MCA execution which happens more toward the end of the build? I'm open to being convinced otherwise :)

On Distro-factory we only do release notes once a mix succeed. I would not even bother to create those if the mix cannot be created in the first place and we dont  fast forward publishing artificats if build does not looks good.

**Comment by mbelluzzo** [comment]
But yes, we dont want to depend on MCA. This code needs to be able to compare the current state (mixer dir, work dir etc) with the latest version on staged folder, if any (needs to properly handle the null case).

**Review by mbelluzzo — CHANGES_REQUESTED** [review]
Needs re-work.

**Pull request closed without merging**
